### ISSUE TITLE
Cannot get the love-lace card to work

### ISSUE THREAD

**Issue by asapkota** [dmulcahey/zha-network-visualization-card#16]
I installed all the req via HACS and updated the config. When I add the custom card, I get the following error:

2020-03-03 08:24:32 ERROR (MainThread) [frontend.js.latest.202002205] http://X.X.X.X:8123/community_plugin/zha-network-card/zha-network-card.js:3:11 Uncaught ReferenceError: transpose is not defined

Please advise.

**Comment by colemannugent** [comment]
So I'm running into the same issue. The strange thing is, I can't find the offending code anywhere in this repo or it's sister zha-map repo. Here's a snippet of the broken code I can't locate:

```js
/** some helper functions, mmmh, am I the only one needing those? Am I doing something wrong? */
// typical [[1,2,3], [6,7,8]] to [[1, 6], [2, 7], [3, 8]] converter
transpose = m => m[0].map((x, i) => m.map(x => x[i]));
```

The actual error occurs on the last line in the snippet.

Google searches for that exact text return nothing either. I thought it could be an extension that I have installed, but grepping my Firefox install for those strings returned no matches. Neither did searching vis-network, home-assistant/core, home-assistant/frontend, hacs/integration, or hacs/frontend.

I figure it's worth mentioning that I installed both the card and the integration through HACS. It seems like everyone else having issues also used HACS, so maybe this is related to [zha-ng/zha-map/#11](https://github.com/zha-ng/zha-map/issues/11) in that HACS pulls the master branch which causes issues?

Also if it makes a difference, through the Lovelace raw config editor I added this:

```yaml
resources:
  - type: module
    url: /hacsfiles/zha-network-card/zha-network-card.js
```

Once this is figured out I'll create a PR to document the correct steps to setup this integration.

**Comment by colemannugent** [comment]
Found it. This code seems to come from [custom-cards/flex-table-card](https://github.com/custom-cards/flex-table-card/blob/master/flex-table-card.js#L4) repo. Hmm, maybe the `type` should be `js` in our resources block...

**Comment by colemannugent** [comment]
Okay @asapkota I've got it figured out. You can't use HACS to install this card because the one listed in HACS isn't this repo!

You'll need to download the `zha-network-visualization-card.js` file from this repo and put it inside a folder called `zha-network-visualization-card` in the same folder that HACS installs its custom cards (for me it was `www/community/zha-network-visualization-card`).

Then make sure you have this added to your Lovelace config:

```yaml
resources:
  - type: module
    url: >-
      /hacsfiles/zha-network-visualization-card/zha-network-visualization-card.js
```

@dmulcahey This issue can probably be closed now. It might be worth adding this info to the README so that newcomers like me don't spam you with issues about this in the future :smile:

**Comment by asapkota** [comment]
Thanks @colemannugent. Will try this
